# Change these first
owner: volcar144 # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

sites:
  - name: gitea
    url: https://git.archiem.top
  - name: Short URL
    url: https://l.archiem.top
  - name: API
    url: https://api.archiem.top/health
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.archiem.top
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "AMT Service Status Dashboard"
  introMessage: Real-time status and historical uptime reports for all monitored services. Stay informed about outages, maintenance, and performance metrics.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
